//TODO: Apply "credencials: 'include'" to create, update, and delete functions too. 


const API_URL = "http://localhost:8080/tasks";
// const USER_NAME = "user"; // Default user to use in Basic Authentication
// const PASSWORD = "8d51c18d-20e0-4249-847c-63f8d7ba862c"; // Password generated by Spring during initialization

// const BASIC_AUTH = 'Basic ' + btoa(USER_NAME + ':' + PASSWORD);
 
const getHeaders = () => {
// BASIC_AUTH config
  // return {
  //   'Content-Type': 'application/json',
  //   'Authorization': BASIC_AUTH
  // };

// FORM_AUTH config
  return {
    'Content-Type': 'application/json'
  };
};

export const getAllTasks = async () => {
  const response = await fetch(API_URL, {
    method: 'GET',
    headers: getHeaders(),
    credentials: 'include'
  });

  if (!response.ok) {
    throw new Error(`API Error: ${response.statusText}`);
  }

  return await response.json();
};

export const createTaskService = async (taskTitle, taskDescription) => {
  const response = await fetch(API_URL, {
    method: "POST",
    headers: getHeaders(),
    // Send a JSON object string matching the DTO structure
    body: JSON.stringify({ title: taskTitle, description: taskDescription }),
    credentials: 'include'
  });

  if (!response.ok) {
    throw new Error("Failed to create task");
  }

  return await response.json(); // Return the created task (with the new ID)
};

export const deleteTaskService = async (id) => {
  const response = await fetch(`${API_URL}/${id}`, {
    method: "DELETE",
    headers: getHeaders(),
    credentials: 'include'
  });

  if (!response.ok) {
    throw new Error("Failed to delete task");
  }

  // Don't return .json() because the API don't return response in this method
  return true;
};

export const updateTaskService = async (id, task) => {
  const response = await fetch(`${API_URL}/${id}`, {
    method: "PUT",
    headers: getHeaders(),
    body: JSON.stringify(task),
    credentials: 'include'
  });

  if (!response.ok) {
    throw new Error("Failed to update task");
  }

  return await response.json();
};
